title: Food, games, and Mini-schnauzers!
author: shasN
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about eating, petting my dog, and playing video games

# social links
twitter_username: rand0mzebra
github_username:  shasN

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
